---
- name: Create temp file for config
  delegate_to: localhost
  ansible.builtin.tempfile:
    state: file
  register: config_file

- name: Create config
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{ config_file.path }}"
    content: "{{ cfssl_config | to_json }}"
    mode: "0640"

- name: Create temp file for CSR
  delegate_to: localhost
  ansible.builtin.tempfile:
    state: file
  register: csr_file

- name: Create CSR
  delegate_to: localhost
  ansible.builtin.copy:
    dest: "{{ csr_file.path }}"
    content: "{{ cfssl_csr_template | to_json }}"
    mode: "0640"

- name: Generate cert
  delegate_to: localhost
  changed_when: true
  ansible.builtin.command: "cfssl gencert -config {{ config_file.path }} -profile {{ cfssl_generate_profile }} {{ csr_file.path }}"
  register: cert

- name: Get intermediate cert
  delegate_to: localhost
  changed_when: true
  ansible.builtin.command: "cfssl info -config {{ config_file.path }}"
  register: intermediate_cert

- name: Show generated cert
  ansible.builtin.debug:
    msg: "{{ cert.stdout | from_json }}"
    verbosity: 1

- name: Create directory for generated certs
  become: "{{ cfssl_become }}"
  ansible.builtin.file:
    path: "{{ cfssl_generated_cert_path }}"
    state: "directory"
    mode: "{{ cfssl_generated_cert_path_permission | default(omit) }}"

- name: Create certificate
  become: "{{ cfssl_become }}"
  ansible.builtin.copy:
    dest: "{{ cfssl_generated_cert_path }}/{{ cfssl_certificate_filename }}"
    content: "{{ (cert.stdout | from_json).cert }}"
    mode: "{{ cfssl_generated_cert_permission | default(omit) }}"

- name: Create full chain certificate
  become: "{{ cfssl_become }}"
  ansible.builtin.copy:
    dest: "{{ cfssl_generated_cert_path }}/{{ cfssl_certificate_full_chain_filename }}"
    content: "{{ (cert.stdout | from_json).cert ~ (intermediate_cert.stdout | from_json).certificate }}"
    mode: "{{ cfssl_generated_cert_permission | default(omit) }}"

- name: Create key
  become: "{{ cfssl_become }}"
  ansible.builtin.copy:
    dest: "{{ cfssl_generated_cert_path }}/{{ cfssl_certificate_key_filename }}"
    content: "{{ (cert.stdout | from_json).key }}"
    mode: "{{ cfssl_generated_cert_permission | default(omit) }}"
