---
# tasks file for cloudflare-cfssl

- name: Start CFSSL Docker container
  delegate_to: localhost
  ansible.builtin.import_tasks:
    file: start_cfssl_container.yml

- name: Generate certs
  vars:
    cfssl_csr_cn: "{{ item.cfssl_csr_cn }}"
    cfssl_generate_profile: "{{ item.cfssl_generate_profile }}"
    cfssl_generated_cert_path: "{{ item.cfssl_generated_cert_path }}"
  ansible.builtin.include_tasks:
    file: generate_cert.yml
  loop: "{{ cfssl_generate_certs }}"
